apiVersion: v1
kind: Pod
metadata:
  name: curl-test-svc
spec:
  containers:
    - name: ubuntu
      image: alpine:3.17
      command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache curl
          while true; do
              curl -s http://nginx-service.default.svc.cluster.local
              sleep 1
          done
