apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
data:
  index.html: |
    <html>
    <head>
        <title>Welcome to nginx!</title>
    </head>
    <body>
    <h1>Hello World from $HOSTNAME</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
              name: http-web-svc
          command:
            - /bin/sh
            - -c
            - |
              chmod 777 /usr/share/nginx/html/index.html
              envsubst < /var/www/html/index.html > /usr/share/nginx/html/index.html
              nginx -g 'daemon off;'
          volumeMounts:
            - mountPath: /var/www/html
              name: nginx-index-html
      volumes:
        - name: nginx-index-html
          configMap:
            name: nginx-index-html
            items:
              - key: index.html
                path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
#  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: htto-web
      protocol: TCP
      port: 80
      targetPort: http-web-svc